### ISSUE TITLE
`SyntaxError: Unexpected token )` when building new Application UI

### ISSUE THREAD

**Issue by cfregly** [aws-samples/aws-saas-factory-eks-reference-architecture#49]
```
admin:~/environment/aws-saas-factory-eks-reference-architecture/clients/Application (main) $ ng build --prod
/usr/lib/node_modules/@angular/cli/bin/ng.js:35
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

**Comment by ranjith-aws** [comment]
Thanks for reporting. This doesn't look like it is happening now, most likely fixed by the new updates we did. Closing for now.
