### ISSUE TITLE
Landing page access denied

### ISSUE THREAD

**Issue by blueaglet** [aws-samples/aws-saas-factory-eks-reference-architecture#96]
I successfully deployed the application using both options: with or without custom domain. However when I tried to access the landing page www.mydomain.com, I got access denied message.
What else do I need to do to get it working? Thanks for help!

**Comment by ranjith-aws** [comment]
It could be that the DNS propagation is still happening. Maybe just give it a few and retry? Also, check if the S3 buckets for the Angular apps has files/assets in it?

**Comment by blueaglet** [comment]
I tried to redeploy today to see if DNS propagation was done. But got following error, which didn't occur yesterday.  Has there been any changes in the system somewhere?

9:51:20 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack               | EKSSaaSCluster-aws...sour-1B2LQEIDAZQ4P
10:10:42 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart             | SaaSCluster/chart-...r/Resource/Default
Received response status [FAILED] from custom resource. Message returned: Error: b'Release "controller" does not exist.
Installing it now.\nError: template: nginx-ingress/templates/controller-deployment.yaml:140:4: executing "nginx-ingress/
templates/controller-deployment.yaml" at <include "nginx-ingress.args" .>: error calling include: template: nginx-ingres
s/templates/_helpers.tpl:181:43: executing "nginx-ingress.args" at <.Values.controller.debug.enable>: nil pointer evalua
ting interface {}.enable\n'

Logs: /aws/lambda/EKSSaaSCluster-awscdkawseksKubectl-Handler886CB40B-Hjvjjor9x8Lw

at invokeUserFunction (/var/task/framework.js:2:6)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: f9ebdad5-5970-4dcd-9844-bb654b9b94a7)

**Comment by tobuck-aws** [comment]
@blueaglet thanks for reporting this. I'll be looking at this today to try and bring everything up to current versions of Node and other dependencies. I'll update this issue with my findings.

**Comment by blueaglet** [comment]
@ranjith-aws @tobuck-aws 
Any updates on this issue? I saw some updates on update angular to 17 but don't see other updates yet.
I however got most of app work (pre angular 17 update).  We are thinking to adopt this reference architecture for our development. The first thing I want to do is to finish the product image link. We are storing images in s3 bucket. Each of our products is associated with a set of images. So the product link will lead to display of a set of images. Any advice on how best to implement this? Thanks in advance!

**Comment by tobuck-aws** [comment]
@blueaglet Sorry, I didn't include the landing page in this update. The other pages, however, should work. The landing page is really just another mechanism for invoking the onboarding api.

Re: your question, I'm not sure I understand what you're asking? When you say images, are you talking container images? or like a png image?

**Comment by blueaglet** [comment]
Sorry. I meant png images

**Comment by blueaglet** [comment]
@tobuck-aws I just deployed the latest version  and noticed that Logout for either Admin or Application is not working.

**Comment by blueaglet** [comment]
Just created a new issue #100 to track the logout problem.
